name: Deploy EKS

on:
  push:
    branches: [ main ]

permissions:
  id-token: write   # OIDC
  contents: read

# Set your AWS account ID once; or switch to repo variables below
env:
  AWS_ACCOUNT_ID: 590183795217

concurrency:
  group: eks-deploy-main
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/EKSDeploymentRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Fmt
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false -no-color

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
