name: Lint Terraform

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init
        run: terraform init -backend=false

      - name: Format Check
        run: terraform fmt -check -recursive

      - name: Validate
        run: terraform validate
